server:
  port: 3335

spring:
   application:
    name: microservicecloud-config

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id:  microservicecloud-config3355
    prefer-ip-address: true #访问路径可以显示IP地址


